workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "safe_exam_app"

    scripts:
      - name: Install Dependencies
        script: |
          flutter pub get

      - name: Clean
        script: |
          flutter clean

      - name: Build AAB
        script: |
          flutter build appbundle --release

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    cache:
      paths:
        - ~/.pub-cache
        - build/
