workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      android:
        components:
          - build-tools-34.0.0
          - platform-tools
          - platforms;android-34
          - ndk;27.0.12077973

      vars:
        PACKAGE_NAME: "safe_exam_app"

    caching:
      cache_paths:
        - ~/.pub-cache
        - build/

    scripts:
      - name: Check Flutter version
        script: |
          flutter --version

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Clean build
        script: |
          flutter clean

      - name: Build Android AppBundle (.aab)
        script: |
          flutter build appbundle --release

      - name: Build APK (optional)
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
